# Generated by Django 6.0.3 on 2026-03-28 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_course_code_remove_user_is_suspended_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(default='DEFAULT', max_length=50),
            preserve_default=False,
        ),
    ]
